#!/usr/bin/env bash

KEY=$1
VALUE=$(echo -n $2 | base64)
CFG="$(hostname)-secret"

kubectl get secret ${CFG} -o json | jq --arg key $KEY --arg value $VALUE '.data[$key] = $value'  | kubectl apply -f -