name: Publish Docker image

on:
  push:
    tags: '*'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: login to dockerhub
        run: docker login -u jeffohrstrom -p ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: docker build
        run: docker build -t ood-k8s-utils:latest .
      - name: tag 
        run: |
          if [ -z "$GITHUB_REF" ]; then
            TAG==$(echo $GITHUB_REF | awk -F'/' '{ print $3}')
            docker tag ood-k8s-utils:latest ood-k8s-utils:$TAG
          fi
