name: Publish Docker image

on:
  release:
    types: [published]

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: login to dockerhub
        run: docker login -u jeffohrstrom -p ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: docker build
        run: docker build -t ood-k8s-utils:latest .
      - name: tag 
        run: [ -z "$GITHUB_REF" ] || docker tag ood-k8s-utils:latest ood-k8s-utils:$GITHUB_REF
